apiVersion: v1
kind: Service
metadata:
  name: wanderlust-frontend
  namespace: wanderlust
spec:
  selector:
    app: frontend-dp
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30080 
